### ISSUE TITLE
Progress sync on Hitman 2 doesn't pick up Discover The Yacht challenge in ICA Facility

### ISSUE THREAD

**Issue by nathanchere** [thepeacockproject/Peacock#456] opened 2024-05-09 16:11 UTC
**Describe the bug**

Using the new progression sync for Hitman 2 doesn't pick up Discover The Yacht challenge in ICA Facility.

If I connect normally without Peacock it shows 100% completion of everything on ICA Facility

If I connect to Peacock with progression synced, everything is marked complete except for Discover the Yacht challenge ("Reveal all undiscovered areas on the yacht"). Attempting to complete this challenge again doesn't appear to work either because none of the areas trigger being discovered (always shows 0/5 completion).

**To reproduce**

I can provide my local Peacock userdata if that helps?

**Comment by RDIL** [comment] 2024-05-09 16:12
Duplicate of #447

**Closed by RDIL** 2024-05-09 16:12 UTC
Labels: bug
