### ISSUE TITLE
Broken challenges

### ISSUE THREAD

**Issue by RDIL** [thepeacockproject/Peacock#22] opened 2022-11-13 02:31 UTC
Investigate broken challenges.  See comments on this issue for the full list:

**Comment by moonysolari** [comment] 2022-12-13 21:18
## Rubber Duck Sunday in Bangkok

After it is completed, its tile will be shown in color in the ending screen. However, it will not be shown as checked on the ending screen like other completed challenges. The same thing happens if the target was killed with a propane flask (which I am not sure whether should count towards this challenge or not). Upon finishing a subsequent playthrough, the tile of this challenge will turn back to grey. Going to the Challenges tab in the menu will also show this challenge as unfinished.

![image](https://user-images.githubusercontent.com/118079569/207445010-3d9fcb45-2a91-4538-879f-b182ace87253.png)

**Comment by moonysolari** [comment] 2023-01-02 04:38
# Paris (As of v5.6.2)
## Knockout Punch
Knockout Punch can still be unlocked with Lethal Syringe Mk II and III on Viktor.
## Speechless
Can be unlocked in game. Does not save. Does not appear in color on the end-of-mission challenge summary. 
## Close Personal Protection
Can be unlocked in game. Does not save. Does not appear in color on the end-of-mission challenge summary.

**Comment by AnthonyFuller** [comment] 2023-01-02 04:41
Knockout Punch is not a bug, it is the same on official servers. We are not fixing that.

**Comment by moonysolari** [comment] 2023-01-07 05:33
# Colorado
## Quicker Than the Eye

Tracks progress and unlocks in-game, but neither saves nor appears in color on the end-of-mission challenge summary page.

**Comment by moonysolari** [comment] 2023-01-07 06:58
| Resolved | Challenge | Location | Bar fills up in-game? | Unlocks in-game? | Shown in color on ending screen? | Ticked on ending screen? | Saves? | Game | Peacock | Comments | 
| :---: | :---: | :---:  | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| No | Rubber Duck Sunday | Bangkok | N/A | No | Yes | No | No | 3.130 | v5.6.2 | Propane flasks currently also count. |
| No | Speechless | Paris | N/A | Yes | No | No | No | 3.130 | v5.6.2 | |
| No | Close Personal Protection | Paris | N/A | Yes | No | No | No | 3.130 | v5.6.2 | |
| No | The Personal Touch | Paris |  Yes | Yes | Yes | No | No | 3.130 | v5.6.2 | |
| No | Quicker Than the Eye | Colorado | Yes | Yes | Yes | No | No |  3.130 | v5.6.2 | |
| No | Where is Everybody? | Colorado | Yes | Yes | Yes | No | No |  3.130 | v5.6.2 | |
| No | Chameleon | Multiple | Yes | Yes | Yes | No | No |  3.130 | v5.6.2 | Also does not save between sessions. |

**Comment by AnthonyFuller** [comment] 2023-01-07 10:24
RE: Rubber Duck Sunday

If propane counts on Peacock, it also likely counts on official servers so it's like Knockout Punch. We won't be fixing that.

**Comment by moonysolari** [comment] 2023-01-07 11:11
> RE: Rubber Duck Sunday
> 
> If propane counts on Peacock, it also likely counts on official servers so it's like Knockout Punch. We won't be fixing that.

Yeah I know because Peacock gets its jsons from official. Still it would be better to make sure if possible.

**Comment by moonysolari** [comment] 2023-03-10 06:02
Love Triangle doesn't save. Might be a state machine parser bug. First reported in [Discord](https://discord.com/channels/826809653181808651/1082856658142760991).

**Comment by LennardF1989** [comment] 2023-04-02 12:25
Shouldn't this one be closed @moonysolari ?

**Comment by moonysolari** [comment] 2023-04-02 16:49
> Shouldn't this one be closed @moonysolari ?

Yes I think this can be closed. It has been a long time since the last time a challenge was reported to be broken, and they can have their own issues when other broken challenges are discovered.

**Closed by moonysolari** 2023-04-02 16:49 UTC
Labels: bug, challenges
